
[package]
    archivePath = "https://d4i3qtqj3r0z5.cloudfront.net/omni.ai.chat_usd.bundle-2.0.4%2B107.3.0.cp311.zip"

    [package.target]

        [package.target.python]
            0 = "cp311"

        [package.target.kit]
            0 = "107.3.0"

    [package.publish]
        kitVersion = "107.3.0+master.187713.ec24b4bc.gl"
        date = 1747847590
        buildNumber = "2022.2.0-beta.8+master.2474.0f8ade4c.gl"
        repoName = "kit-template"
        signed = 1
